import type { Job } from "@/components/JobCard";

export const sampleJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "TechFlow",
    location: "San Francisco, CA",
    salary: "$150k - $190k",
    type: "Full-time",
    posted: "2h ago",
    logo: "TF",
    tags: ["React", "TypeScript", "Remote"],
  },
  {
    id: "2",
    title: "Product Designer",
    company: "Pixelab",
    location: "New York, NY",
    salary: "$120k - $155k",
    type: "Full-time",
    posted: "5h ago",
    logo: "PX",
    tags: ["Figma", "UX", "Hybrid"],
  },
  {
    id: "3",
    title: "Backend Developer",
    company: "DataNova",
    location: "Austin, TX",
    salary: "$130k - $170k",
    type: "Full-time",
    posted: "1d ago",
    logo: "DN",
    tags: ["Node.js", "PostgreSQL", "Remote"],
  },
  {
    id: "4",
    title: "Mobile Engineer",
    company: "AppSphere",
    location: "Seattle, WA",
    salary: "$140k - $180k",
    type: "Contract",
    posted: "1d ago",
    logo: "AS",
    tags: ["React Native", "iOS", "Android"],
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "CloudBase",
    location: "Remote",
    salary: "$125k - $160k",
    type: "Full-time",
    posted: "2d ago",
    logo: "CB",
    tags: ["AWS", "Kubernetes", "CI/CD"],
  },
  {
    id: "6",
    title: "Marketing Manager",
    company: "GrowthLab",
    location: "Los Angeles, CA",
    salary: "$95k - $125k",
    type: "Full-time",
    posted: "3d ago",
    logo: "GL",
    tags: ["SEO", "Content", "Analytics"],
  },
  {
    id: "7",
    title: "Data Scientist",
    company: "IntelliCore",
    location: "Boston, MA",
    salary: "$135k - $175k",
    type: "Full-time",
    posted: "3d ago",
    logo: "IC",
    tags: ["Python", "ML", "Remote"],
  },
];
